[theme]
base                     = "light"
primaryColor             = "#4caf50"
backgroundColor          = "#145a20"
secondaryBackgroundColor = "#1b5e20"
textColor                = "#ffffff"
font                     = "sans serif"
